<?php

namespace App\Http\Resources;

use App\Models\Form1bSubmission;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @mixin Form1bSubmission
 */
class Form1bSubmissionResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'case_id' => $this->case_id,
            'date_identified' => $this->date_identified,
            'date_registered' => $this->date_registered,
            'date_reopened' => $this->date_reopened,
            'caseworker_id' => $this->caseworker_id,
            'agency' => $this->agency,
            'identification_source' => $this->identification_source,
            'identification_source_sector' => $this->identification_source_sector,
            'identification_source_other' => $this->identification_source_other,
            'first_name' => $this->first_name,
            'middle_name' => $this->middle_name,
            'last_name' => $this->last_name,
            'other_names' => $this->other_names,
            'dob' => $this->dob,
            'age' => $this->age,
            'age_estimated' => $this->age_estimated,
            'sex' => $this->sex,
            'birth_registration' => $this->birth_registration,
            'has_id' => $this->has_id,
            'id_type' => $this->id_type,
            'id_number' => $this->id_number,
            'nationality_status' => $this->nationality_status,
            'displacement_status' => $this->displacement_status,
            'displacement_status_other' => $this->displacement_status_other,
            'nationality' => $this->nationality,
            'disability_status' => $this->disability_status,
            'disability_other' => $this->disability_other,
            'marital_status' => $this->marital_status,
            'ethnic_affiliation' => $this->ethnic_affiliation,
            'religion' => $this->religion,
            'languages_spoken' => $this->languages_spoken,
            'care_type' => $this->care_type,
            'care_type_other' => $this->care_type_other,
            'care_description' => $this->care_description,
            'current_address' => $this->current_address,
            'area_type' => $this->area_type,
            'contact_method' => $this->contact_method,
            'caregiver_first_name' => $this->caregiver_first_name,
            'caregiver_middle_name' => $this->caregiver_middle_name,
            'caregiver_last_name' => $this->caregiver_last_name,
            'caregiver_dob' => $this->caregiver_dob,
            'caregiver_age' => $this->caregiver_age,
            'caregiver_age_estimated' => $this->caregiver_age_estimated,
            'caregiver_sex' => $this->caregiver_sex,
            'caregiver_has_id' => $this->caregiver_has_id,
            'caregiver_id_type' => $this->caregiver_id_type,
            'caregiver_id_number' => $this->caregiver_id_number,
            'caregiver_nationality_status' => $this->caregiver_nationality_status,
            'caregiver_displacement_status' => $this->caregiver_displacement_status,
            'caregiver_has_disabilities' => $this->caregiver_has_disabilities,
            'caregiver_disabilities_detail' => $this->caregiver_disabilities_detail,
            'caregiver_related_to_child' => $this->caregiver_related_to_child,
            'caregiver_relationship' => $this->caregiver_relationship,
            'caregiver_knows_family' => $this->caregiver_knows_family,
            'care_arrangement_start' => $this->care_arrangement_start,
            'caregiver_willing_to_continue' => $this->caregiver_willing_to_continue,
            'caregiver_unwilling_reason' => $this->caregiver_unwilling_reason,
            'caregiver_is_legal_guardian' => $this->caregiver_is_legal_guardian,
            'caregiver_contact' => $this->caregiver_contact,
            'household_adults' => $this->household_adults,
            'household_children' => $this->household_children,
            'main_caregiver_under_18' => $this->main_caregiver_under_18,
            'household_members' => $this->whenLoaded('householdMembers', fn () => $this->householdMembers->map(fn ($m) => [
                'id' => $m->id,
                'full_name' => $m->full_name,
                'age' => $m->age,
                'relationship' => $m->relationship,
            ])),
            'situation_description' => $this->situation_description,
            'risks_identified' => $this->risks_identified,
            'justice_system_status' => $this->justice_system_status,
            'mother_first_name' => $this->mother_first_name,
            'mother_middle_name' => $this->mother_middle_name,
            'mother_last_name' => $this->mother_last_name,
            'mother_alive' => $this->mother_alive,
            'mother_death_note' => $this->mother_death_note,
            'mother_nationality_status' => $this->mother_nationality_status,
            'mother_displacement_status' => $this->mother_displacement_status,
            'mother_has_disabilities' => $this->mother_has_disabilities,
            'mother_disabilities_detail' => $this->mother_disabilities_detail,
            'mother_in_contact' => $this->mother_in_contact,
            'mother_contact_method' => $this->mother_contact_method,
            'mother_dob' => $this->mother_dob,
            'mother_age' => $this->mother_age,
            'mother_age_estimated' => $this->mother_age_estimated,
            'mother_has_id' => $this->mother_has_id,
            'mother_id_type' => $this->mother_id_type,
            'mother_id_number' => $this->mother_id_number,
            'father_first_name' => $this->father_first_name,
            'father_middle_name' => $this->father_middle_name,
            'father_last_name' => $this->father_last_name,
            'father_alive' => $this->father_alive,
            'father_death_note' => $this->father_death_note,
            'father_nationality_status' => $this->father_nationality_status,
            'father_displacement_status' => $this->father_displacement_status,
            'father_has_disabilities' => $this->father_has_disabilities,
            'father_disabilities_detail' => $this->father_disabilities_detail,
            'father_in_contact' => $this->father_in_contact,
            'father_contact_method' => $this->father_contact_method,
            'father_dob' => $this->father_dob,
            'father_age' => $this->father_age,
            'father_age_estimated' => $this->father_age_estimated,
            'father_has_id' => $this->father_has_id,
            'father_id_type' => $this->father_id_type,
            'father_id_number' => $this->father_id_number,
            'immediate_family_members' => $this->whenLoaded('familyMembers', fn () => $this->familyMembers->map(fn ($m) => [
                'id' => $m->id,
                'full_name' => $m->full_name,
                'age' => $m->age,
                'relationship' => $m->relationship,
                'address' => $m->address,
            ])),
            'has_urgent_needs' => $this->has_urgent_needs,
            'needs_family_tracing' => $this->needs_family_tracing,
            'immediate_needs' => $this->whenLoaded('immediateNeeds', fn () => $this->immediateNeeds->map(fn ($n) => [
                'id' => $n->id,
                'category' => $n->category,
                'category_other' => $n->category_other,
                'summary_reasons' => $n->summary_reasons,
                'action_taken' => $n->action_taken,
            ])),
            'risk_level' => $this->risk_level,
            'risk_summary' => $this->risk_summary,
            'caseworker_name' => $this->caseworker_name,
            'caseworker_date' => $this->caseworker_date,
            'caseworker_signature' => $this->caseworker_signature,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
